
<?php


function movie_reservation_theme($existing, $type, $theme, $path)
{
  return array(
    'movie_list' => array(
      'variables' => array('movies' => array(), 
        'title' => '', 
        'genres' => array(), 
        'days' => array())
        
    )
  );
}

function movie_reservation_page_attachments(array &$page) {
  $page['#attached']['library'][] = 'movie_reservation/movie_reservation_css';
}